kind: pipeline
type: docker
name: DAFLPipeline

steps:
- name: app-build
  image: cirrusci/flutter:stable
  commands:
    - flutter doctor
    - flutter build

- name: code-analysis
  image: cirrusci/flutter:stable
  environment:
      SONAR_TOKEN:
        from_secret: sonar_token
  settings:
      sources: ./Sources
  commands:
  - cd Sources/dafl_project_flutter
