# database container deployment
  - name: deploy-container-dafl
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: alpine:3.16
        CONTAINERNAME: dafl
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_POSTGRESQL_ROOT_PASSWORD:
          from_secret: db_root_password
        CODEFIRST_CLIENTDRONE_ENV_POSTGRESQL_DATABASE:
          from_secret: db_database
        CODEFIRST_CLIENTDRONE_ENV_POSTGRESQL_USER:
          from_secret: db_user
        CODEFIRST_CLIENTDRONE_ENV_POSTGRESQL_PASSWORD:
          from_secret: db_password